from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('TCA9548A_Examples', src, depend = ['TCA9548A_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')