from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('TCA9548A', src, depend = ['PKG_USING_TCA9548A'], CPPPATH = CPPPATH)

Return('group')